---
title: "05-Filter out predictors based on descriptive analysis, 
        information value and simple logit regression results"
author: "gmlang"
date: "April 3, 2015"
output: pdf_document
---

```{r}
# settings for RMarkdown 
library(knitr)
opts_chunk$set(comment = "", warning = FALSE, message = FALSE, tidy = FALSE,
               echo = TRUE, fig.width = 4, fig.height = 4, dev = 'pdf')
options(width = 100, scipen = 5, digits = 5)
```

### Load data
```{r}
# set path and load data
proj_path = '~/Movies/masterr-vids/predict-bad-customers'
data_path = file.path(proj_path, 'data')
load(file.path(data_path, 'cleaned-02.rda'))
load(file.path(data_path, 'cleaned-03.rda'))
load(file.path(data_path, 'cleaned-04.rda'))
```

### Discard these predictors
```{r}
drop_cat1 = intersect(intersect(iv_cat_none, IV_none), iv_non_sig)
drop_con1 = intersect(intersect(iv_con_none, IV_none), iv_non_sig)

drop_cat2 = intersect(intersect(iv_cat_weak, IV_none), iv_non_sig)
drop_con2 = intersect(intersect(iv_con_weak, IV_none), iv_non_sig)

drop_cat = c(drop_cat1, drop_cat2)
drop_con = c(drop_con1, drop_con2)

print(drop_cat)
print(drop_con)
```

### Update predictors and save
```{r}
iv_cat = c(iv_cat_none, iv_cat_weak, iv_cat_strong)
iv_cat = iv_cat[!iv_cat %in% drop_cat]
print(iv_cat)

iv_con = c(iv_con_none, iv_con_weak, iv_con_strong)
iv_con = iv_con[!iv_con %in% drop_con]
print(iv_con)

save(dat, iv_cat, iv_con, file=file.path(data_path, "cleaned-05.rda"))
```