---
title: "03-Calculate Weight of Evidence(WOE) and Information Value (IV)"
author: "gmlang"
date: "April 3, 2015"
output: pdf_document
---

```{r}
# settings for RMarkdown 
library(knitr)
opts_chunk$set(comment = "", warning = FALSE, message = FALSE, tidy = FALSE,
               echo = TRUE, fig.width = 4, fig.height = 4, dev = 'pdf')
options(width = 100, scipen = 5, digits = 5)
```

### Load data
```{r}
# set path and load data
proj_path = '~/Movies/masterr-vids/predict-bad-customers'
help_path = file.path(proj_path, "helper")
source(file.path(help_path, "calcIV.R"))

data_path = file.path(proj_path, 'data')
file_path = file.path(data_path, 'cleaned-02.rda')
load(file_path)
```

### Weight of Evidence (WOE) and Information Value (IV)
```{r, results='asis'}
predictors = c(iv_cat_strong, iv_cat_weak, iv_cat_none, iv_con_strong,
               iv_con_weak, iv_con_none)
IV = rep(0, length(predictors))
for (i in 1:length(predictors)) {
        var = predictors[i]
        WOE_IV = calcIV(dat, "bad", var)
        print(kable(WOE_IV, row.names = FALSE, format = "pandoc", caption=var))
        cat("\n")
        
        # sum up IV components for each predictor
        IV[i] = sum(WOE_IV$IV)
}

IV = data.frame(predictor = predictors, IV=IV)
IV$predictive_power[IV$IV < 0.02] = "Useless"
IV$predictive_power[0.02 <= IV$IV & IV$IV < 0.1] = "Weak"
IV$predictive_power[0.1 <= IV$IV & IV$IV < 0.3] = "Medium"
IV$predictive_power[0.3 <= IV$IV & IV$IV < 0.5] = "Strong"
IV$predictive_power[0.5 <= IV$IV] = "Too good to be true"
kable(IV, row.names = FALSE, format = "pandoc", caption="Information Value")
```

The following info is taken from a blog post:

* IV < 0.02 => Useless for prediction
* 0.02 ~ 0.1 => Weak predictor
* 0.1 ~ 0.3 => Medium predictor
* 0.3 ~ 0.5 => Strong predictor
* IV > 0.5 => Suspicious or too good to be true

### Collect predictors into different groups based on predictive power
```{r}
IV_none = as.character(with(IV, predictor[predictive_power=="Useless"]))
print(IV_none)

IV_weak = as.character(with(IV, predictor[predictive_power=="Weak"]))
print(IV_weak)

IV_medium = as.character(with(IV, predictor[predictive_power=="Medium"]))
print(IV_medium)

IV_strong = as.character(with(IV, predictor[predictive_power=="Strong"]))
print(IV_strong)

IV_extra_strong = as.character(with(IV, predictor[predictive_power=="Too good to be true"]))
print(IV_extra_strong)
```

### save
```{r}
save(IV_none, IV_weak, IV_medium, IV_strong, IV_extra_strong, 
     file = file.path(data_path, 'cleaned-03.rda'))
```